### ISSUE TITLE
Can't convert item to NodeType when using array type without defined items

### ISSUE THREAD

**Issue by SirMishaa** [Grafikart/OpenApiToTS#4]
Hello, I'm sorry but I'm back 

It looks like when we're using an array as type, it cannot convert it to NodeType :
```yml
{
  type: 'array',
  description: 'The allowed mime types for the document (image/jpeg, image/png, application/pdf)'
}
VVVV From VVVV
{
  type: 'array',
  description: 'The allowed mime types for the document (image/jpeg, image/png, application/pdf)'
}

Error: Can't convert item to NodeType
    at SchemaParser.itemToNode (file:///Users/mishaa/yago/seraphinWeb/node_modules/@grafikart/o2ts/dist/SchemaParser.js:221:19)
    at SchemaParser.itemToNode (file:///Users/mishaa/yago/seraphinWeb/node_modules/@grafikart/o2ts/dist/SchemaParser.js:201:57)
    at SchemaParser.convertToCode (file:///Users/mishaa/yago/seraphinWeb/node_modules/@grafikart/o2ts/dist/SchemaParser.js:27:57)
    at file:///Users/mishaa/yago/seraphinWeb/node_modules/@grafikart/o2ts/dist/generator.js:13:26
```
Caused by (working when changing array to string)
```yml
fileMimeTypes:
  type: array
  description: The allowed mime types for the document (image/jpeg, image/png, application/pdf)
exampleImages:
  type: array
  description: The example images of the document that will be show in a modal
  items:
    type: string
    example: https://example.com/example-image.png
```

The full OpenAPI file can be found here : https://gist.github.com/SirMishaa/7e80f67943cc8ffda5532f0506dd0db9#file-document-upload-api-yaml-L271-L279
(Basically, that's the same as before but with an additional type, you can update your test with it if needed) 

Thank you !
